#!/usr/bin/env python
# encoding: utf-8

import sys
from todobase import findnextidx, call

if sys.argv[1] == 'add':
  if __name__ == '__main__':
    args = sys.argv[2:]
    if '[]' in args:
      args[args.index('[]')] = '[%d]' % findnextidx(args)
    print call('add', args)
else:
  print call(sys.argv[1], sys.argv[2:])
