#!/usr/bin/env python
# encoding: utf-8

import sys
from todobase import findnextidx, call, gettodoline

if sys.argv[1] == 'append':
  if __name__ == '__main__':
    args = sys.argv[2:]
    if '[]' in args:
      t = gettodoline(int(args[0]))
      args[args.index('[]')] = '[%d]' % findnextidx(t.line.split(' '))
    print call('append', args)
else:
  print call(sys.argv[1], sys.argv[2:])
